version: '3'

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: flask-rq-apps:master
    ports:
      - "9300:9300"
    env_file:
      - .env
    volumes:
      - .:/app
    command: flask run -h 0.0.0.0 -p 9300 --reload

  rq_dashboard:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: flask-rq-apps:master
    ports:
      - "8900:8900"
    env_file:
      - .env
    volumes:
      - .:/app
    command: rq-dashboard -b 0.0.0.0 -p 8900 --username ${RQ_DASHBOARD_USERNAME} --password ${RQ_DASHBOARD_PASSWORD} -u ${REDIS_URL}
    depends_on:
      - redis

  rq:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: flask-rq-apps:master
    env_file:
      - .env
    volumes:
      - .:/app
    command: rq worker -u ${REDIS_URL}
    depends_on:
      - redis

  redis:
    image: redis:5-alpine
    command: redis-server --requirepass ${REDIS_PASSWORD}
    env_file:
      - .env
