version: '3'

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: flask-rq-apps:master
    ports:
      - "9300:9300"
    env_file: .env
    volumes:
      - .:/app
    command: flask run -h 0.0.0.0 -p 9300 --reload
